pin:
    path: ""
    bin: ""
    pintool-src: 
        arity: ""
        type: ""
        couple: ""
        alloc: ""
        uaf: ""
    pintool-obj:
        arity: ""
        type: ""
        couple: ""
        alloc: ""
        uaf: ""
        memmap: ""
res:
    path: ""
log:
    path: ""
